name: RetinalArchetype
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.2.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - pytorch=2.6.0         # CPU版 or GPU版をお好みで
  - torchvision=0.15.2
  - tqdm=4.65.0
  - opencv=4.10.0          # conda-forge から
  - pip                    # archetypes は pip 経由インストール
  - pip:
    - archetypes==0.6.2